image: python:3.7.3

pipelines:
  branches:
    master:
      - step:
          name: "Build"
          script:
            - apt-get update
            - apt-get install -y zip
            - zip -r application.zip .
          artifacts:
            - application.zip  
      - step:
          name: "Deploy"
          deployment: production
          script:
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.6.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_KEY
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_KEY
                AWS_DEFAULT_REGION: $AWS_REGION
                S3_BUCKET: $S3_BUCKET
                APPLICATION_NAME: $AWS_APPLICATION_NAME
                ENVIRONMENT_NAME: $AWS_ENV_NAME
                ZIP_FILE: 'application.zip' 